---
version: '3'

services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password --mysqlx=0
        environment:
            - MYSQL_HOST=localhost
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=skyapi
            - MYSQL_USER=skyapi
            - MYSQL_PASSWORD=skiapi
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        ports:
            - "3306:3306"
        volumes:
            - "./db:/var/lib/mysql"